// Alerts API — matches ALERTS_API.md exactly.
//   GET   /api/v1/alerts
//   GET   /api/v1/alerts/{alertId}
//   PATCH /api/v1/alerts/{alertId}/acknowledge
//   PATCH /api/v1/alerts/{alertId}/resolve
//
// Alerts are never created directly by users — they're generated by the
// platform after policy evaluation (ADR-011), so there's no POST here.

import { apiFetch, toQueryString, MOCK_MODE, ApiError } from "../apiClient.js";
import { db } from "../mockDb.js";

function delay(ms = 350) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

export async function listAlerts(params = {}) {
  if (MOCK_MODE) {
    await delay();
    return db.getAlerts(params);
  }
  return apiFetch(`/alerts${toQueryString(params)}`);
}

export async function getAlert(alertId) {
  if (MOCK_MODE) {
    await delay();
    const alert = db.getAlert(alertId);
    if (!alert) throw new ApiError("NOT_FOUND", `Alert '${alertId}' was not found`);
    return alert;
  }
  return apiFetch(`/alerts/${alertId}`);
}

export async function acknowledgeAlert(alertId) {
  if (MOCK_MODE) {
    await delay();
    // Uppercase to match the real Backend's AlertStatus enum — see
    // CONTRACT-010/STATE-007.
    return db.updateAlertStatus(alertId, "ACKNOWLEDGED");
  }
  return apiFetch(`/alerts/${alertId}/acknowledge`, { method: "PATCH" });
}

export async function resolveAlert(alertId) {
  if (MOCK_MODE) {
    await delay();
    return db.updateAlertStatus(alertId, "RESOLVED");
  }
  return apiFetch(`/alerts/${alertId}/resolve`, { method: "PATCH" });
}
