flowchart TD

Observation

Observation --> Context

Observation --> Events

Observation --> Metadata

Events --> Event1["Event"]

Events --> Event2["Event"]

Event1 --> Header

Event1 --> Payload

Event2 --> Header

Event2 --> Payload