flowchart TD

subgraph Public_Zone["Public Zone"]
Internet["Internet"]
Dashboard["Dashboard"]
end

subgraph Application_Zone["Application Zone"]
Backend["Backend API"]
end

subgraph Internal_Zone["Internal Services"]
Queue["Queue"]
ML["ML Service"]
Database["Database"]
end

Internet --> Dashboard

Dashboard --> Backend

Backend --> Queue

Backend --> Database

Queue --> ML